---
title: "Advanced R 研讨"
subtitle: "水平测试"
author: "罗智超Rokia.org"
output: 
  pdf_document: 
    fig_caption: yes
    keep_tex: yes
    latex_engine: xelatex
    toc: yes
header-includes:
- \usepackage{xeCJK}
---


# 水平测试

请独立完成以下测试，并记录完成以下每道测试所花费的时间

## 向量运算

- 测试：编写一个函数findNum(x,tag,l)计算在x向量中数字tag连续出现k次的位置。

```{r,eval=FALSE}
#x<- c(1,0,0,1,1,1,0,1,1)
#计算结果为：c(4,5,8)
#x是输入向量
#k是1连续出现的长度
#tag是待查的数字

findRuns <- function(x,tag,k) {
  n <- length(x)
  runs <- vector(length=n)
  count <- 0
  for (i in 1:(n-k+1)) {
    if (all(x[i:(i+k-1)]==tag)) {
      count <- count + 1
      runs[count] <- i
    }
  }
  if (count > 0) {
    runs <- runs[1:count]
  } else runs <- NULL
  return(runs)
}
x<- c(1,0,0,1,1,1,0,1,1)

findRuns(x,tag=0,2)


```


## 数据结构

- 测试：计算每天最低气温和最高气温的差值

```{r,eval=FALSE}
# 计算每天最低气温和最高气温的差值
library(reshape2)
raw <- read.delim("data/weather.txt",check.names = F, na.strings = ".")
raw.tidy <- melt(raw,id = c("year", "month", "element"),variable.name = "day", na.rm = TRUE)
raw <- raw.tidy[, c("year", "month", "day","element", "value")]
tidy <- dcast(raw, year + month + day ~ element,value.var = "value")
tidy$range<-tidy$tmax-tidy$tmin
head(tidy)
```

## 分组处理

- 测试：计算每个航空公司(UniqueCarrier)每个月到达延误时间(ArrDelay)的十分位(quantile)的均值。

```{r,eval=FALSE}
#计算hfflights
library(dplyr)
library(hflights)

rs<-na.omit(hflights) %>% 
  select(UniqueCarrier,Year,Month,ArrDelay) %>%
  group_by(UniqueCarrier,Year,Month) %>%
  mutate(quan=findInterval(ArrDelay,quantile(ArrDelay,seq(0,1,0.1)),rightmost.closed = TRUE)) %>% 
  group_by(UniqueCarrier,Year,Month,quan) %>%
  summarise(avgQuan=mean(ArrDelay,na.rm=T))


```

